### ISSUE TITLE
CameraShow line   VideoOutPut.WriteVideoFrame(eventArgs.Frame, DateTime.Now - beginTime - parseSpan);

### ISSUE THREAD

**Issue by JoeyJia** [yangjinming1062/RecordWin#1]
An exception of type 'AForge.Video.VideoException' occurred in AForge.Video.FFMPEG.dll but was not handled in user code
Additional information: Error while writing video frame. occurred
![图片](https://user-images.githubusercontent.com/24450178/77391017-934bce80-6dd2-11ea-832d-ee4983adfe07.png)

**Comment by yangjinming1062** [comment]
> An exception of type 'AForge.Video.VideoException' occurred in AForge.Video.FFMPEG.dll but was not handled in user code
> Additional information: Error while writing video frame. occurred
> ![图片](https://user-images.githubusercontent.com/24450178/77391017-934bce80-6dd2-11ea-832d-ee4983adfe07.png)

Thank you for your feedback .I have no idea why the exception happened. If it not occurs frequently please use try……catch like:
try{
VideoOutPut.WriteVideoFrame(eventArgs.Frame, DateTime.Now - beginTime - parseSpan);
}
catch { }

**Comment by JoeyJia** [comment]
thanks.
